#-- Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
  toc_levels:     2..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # use_coderay:    false
highlighter:      pygments
excerpt_separator: "<!--more-->"

#-- Permalinks
permalink:            pretty

#-- Setup
title:            TU Delft MSc Geomatics graduation thesis
url:              "tudelftgeomatics.github.io/thesis"
baseurl:          ""


